apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kube-jenkin
  name: kube-jenkin
spec:
  containers:
  - image: docker.io/sambathkumarj/kube-jenkin-cicd:aether
    name: kube-jenkin
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
     - name: dockerhub
status: {}
